######### REDIS DAPHNE 
# version: '3.8'
# services:
#   mosquitto:
#     image: eclipse-mosquitto
#     container_name: mosquitto_2
#     ports:
#       - "1883:1883"
#       - "9001:9001"
#     volumes:
#       - ./mosquitto/config:/mosquitto/config
#     networks:
#       - mqtt_network

#   redis:
#     image: redis:alpine
#     container_name: redis_2
#     ports:
#       - "6379:6379"
#     networks:
#       - mqtt_network

#   web:
#     build: ./django_app
#     container_name: django_app_2
#     command: >
#       sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
#     volumes:
#       - ./django_app:/app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - mosquitto
#       - redis
#     networks:
#       - mqtt_network

# networks:
#   mqtt_network:
#     driver: bridge

####### REDIS UVICORN
version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto_2
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - /etc/localtime:/etc/localtime:ro
    # network_mode: host
    networks:
      - app_network
    environment:
      - TZ=Europe/Istanbul

  # redis:  # REDIS sadece master, proxy yok
  #   image: redis:alpine
  #   container_name: redis
  #   command: ["redis-server", "--appendonly", "yes"] #250915 master-replica sync failover çözümü
  #   volumes: #250915 master-replica sync failover çözümü
  #     - redis-data:/data
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - app_network

  redis-master:
    image: redis:6.2
    command: redis-server --port 6379 
    # command: redis-server --port 6379 --bind 127.0.0.1  #251011 bu ayarla local django makinede redise ulaşım olamaz,django terminalde hata alınır (Error condition on socket for SYNC: Connection refused)
    # restart: unless-stopped # 251011
    volumes:
      - redis_master_data:/data #251011
    ports:
      - "6379:6379"
    networks:
      - app_network
    environment:
      - TZ=Europe/Istanbul

  redis-replica:
    image: redis:6.2
    command: redis-server --replicaof redis-master 6379
    # command: redis-server --port 6379 --replicaof redis-master 6379 --bind 127.0.0.1
    volumes:
      - redis_replica_data:/data #251011
    depends_on:
      - redis-master
    networks:
      - app_network
    environment:
      - TZ=Europe/Istanbul

  haproxy:
    image: haproxy:2.4
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "6380:6379" # dışarıya 6380 portundan açılır
    depends_on:
      - redis-master
      - redis-replica
    networks:
      - app_network
    environment:
      - TZ=Europe/Istanbul

#   web: # REDIS sadece master, proxy yok
#     build: ./django_app
#     container_name: django_app_2
#     volumes:
#       - ./django_app:/app
#       # - .:/app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - redis
#       - mosquitto
#     networks:
#       - app_network
# #deploy memory sınırlama için 250912
#     deploy:
#       resources:
#         limits:
#           memory: 256M

  web: # haproxy ve master-slave redis
    build: ./django_app  # ./django_app klasöründe Dockerfile varlığını kontrol eder
    container_name: django_app_2
    volumes:
      - ./django_app:/app
      # - .:/app
    ports:
      - "8000:8000"
    depends_on:

      - haproxy
      - mosquitto
    networks:
      - app_network
#deploy memory sınırlama için 250912
    deploy:
      resources:
        limits:
          memory: 256M
    # environment:
    #   - TZ=Europe/Istanbul
    #   - REDIS_URL: redis://haproxy:6379
    environment:
      - REDIS_URL=redis://haproxy:6379
      - TZ=Europe/Istanbul

networks:
  app_network:
    driver: bridge


volumes: # 251011 redislere volume tanımlamak için mecburi en alta
  redis_master_data:
  redis_replica_data: